meta_product_name: "Freebird"
meta_title: "Freebird - Artista para seu momento"
meta_description: "A maneira mais fÃ¡cil de contratar artistas para seus eventos."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
